### PR TITLE
feat: support file paths on macs

### PR DESCRIPTION
**Pull request by cs50victor**
WIP. I'll clean up PR later.

### CODE REVIEW

**Comment by yetone** [comment]
LGTM!

**Comment by cs50victor** [comment]
@yetone  I just need to fix / test the `split_file_paths` function to work with file paths with multiple spaces. Also, do you know if mac accessibility api supports file path copying?

**Comment by yetone** [comment]
I'm not sure if it supports.

**Comment by yetone** [comment]
‌‌‌‌Oops, I accidentally merged it.

**Pull request merged**
